### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.vesc_project.VescTool#1]
Application icon seems to be missing on the [Flathub website](https://flathub.org/apps/details/com.vesc_project.VescTool).

**Comment by albfan** [comment]
@barthalion the image is there https://github.com/flathub/com.vesc_project.VescTool/blob/master/com.vesc_project.VescTool.png

I always forget how this works, probably we need 
`com.vesc_project.VescTool.png` somewhere

**Comment by AsciiWolf** [comment]
Well, I think that the icon should be [installed](https://github.com/flathub/com.vesc_project.VescTool/blob/master/com.vesc_project.VescTool.yaml#L25) into `/app/share/icons/hicolor/128x128/apps/com.vesc_project.VescTool.png` instead of the current location. Also, its name should match the `Icon=` entry of VescTool desktop file.

**Comment by barthalion** [comment]
Yes, that's case. By putting the file in location managed by appstream-compose, it has bypassed the icon check.

**Comment by albfan** [comment]
Applying that change icon check fails, should I install in both places or what?

**Comment by barthalion** [comment]
You are not installing a desktop file, so appstream-compose doesn't know where to take the icon from.

**Comment by hfiguiere** [comment]
also the provided icon is not the right size, nor is it square.

**Comment by hfiguiere** [comment]
also this package never had a .desktop, which is the root of all the issues.
